language: ruby
rvm:
  - 3.0.0
services:
  - postgresql
install:
  - bundle
before_script:
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bin/rails db:setup
script:
  - bundle exec rubocop
  - bundle exec rspec
