version: "3.9"

##############################################
# Common config
##############################################

x-app-base: &app-base
  image: app_base
  stdin_open: true
  tty: true
  volumes:
    - .:/app
  environment:
    - REDIS_URL=redis://redis:6379
    - REDIS_PROVIDER=REDIS_URL

##############################################
# Services
##############################################

services:
  web:
    <<: *app-base
    build: .
    ports:
      - "3000:3000"
    command: ./bin/rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - database
      - sidekiq
  database:
    image: postgres:latest
    volumes:
      - .:/app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rails_starter_development
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.0.10-alpine
    command: redis-server --appendonly yes # https://redis.io/topics/persistence
    ports:
      - "6379:6379"
  sidekiq:
    <<: *app-base
    command: bundle exec sidekiq
    depends_on:
      - redis
